### ISSUE TITLE
pdu_thach.py should inherit pdu.py

### ISSUE THREAD

**Issue by T0T4R4** [MinervaCollaboration/minerva-control#2]
PDU.py is meant to be generic. Use object inheritance to bring specificity of the Thach's PDU while ensuring that the public interface is kept untouched. 

Avoid introducing specificity in dependant classes/script like imager.py where recently a flag was added to take care of the thach's pdu. Eventually go down the line of dependancy injection pattern or pass a reference to a PDU object when instanciating the imager.

**Comment by AstroLub** [comment]
Hi - 

As we mentioned in a different comment, we are totally on board with writing child classes for the dependent components (imager, cdk). However, in this case, based on the different structure of the two classes and how they function, we are unsure as to how we can make pdu_thach a child class of PDU.

**Comment by T0T4R4** [comment]
You can start by ensuring that pdu does not contain any specific implementation either. If it does, then move it to a child class as well.
